- task: MSBuild@1
  inputs:
    solution: 'SqlServerDatabase.sln'
    msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
